### ISSUE TITLE
How to get more than lastest 10 posts ?

### ISSUE THREAD

**Issue by momolly1024** [david-fernando/medium-posts-api#13]
hello , 
I can GET the data from api,
but only got the latest ten posts ,
Is there any way to get more older posts?

thanks :）

**Comment by david-fernando** [comment]
I made a GET call from medium User and returned 10 publications, but on your Medium user counted 14 posts.
In principle, the API should return all posts, but I don't know why it's not returning all. 
Thank you for letting me know, I will do my best to fix this.

**Comment by david-fernando** [comment]
Update.
The API get all posts from your rss feed (https://medium.com/@molly1024/feed), but for some reason that I don't know, your feed only shows ten posts.

**Comment by david-fernando** [comment]
Update.
Unfortunately to find that Medium's rss only returns the last ten posts, but I'm looking for alternatives. If this is out of my control then I will have to close this issue.
