### ISSUE TITLE
Images not working anymore

### ISSUE THREAD

**Issue by mc-ducky** [david-fernando/medium-posts-api#403]
There seems to be an issue with the image URLs for posts returning as empty strings. This is affecting the functionality of fetching and displaying images in our application.

**Example:**
For reference, check the API endpoint at https://mediumpostsapi.vercel.app/api/davidfernandodamata21. Here's an example response where the image URL is missing:

```json
{
    "title":"Como fazer dark theme com JavaScript puro",
    "date":"2021-03-07",
    "link":"https://medium.com/david-fernando/como-dark-theme-com-javascript-puro-fc277377447c?source=rss-e1120fb0abef------2",
    "image":"",
    "description":"Um pequeno tutorial de como fazer dark theme com HTML, CSS e JavaScript puro.",
    "tags":["dark-mode","js-tutorial","javascript","tutorial"]
}
```

**Comment by david-fernando** [comment]
Problem solved! Thanks for alerting me!

**Comment by david-fernando** [comment]
Problem solved! Thanks for alerting me!
